### ISSUE TITLE
ModuleNotFoundError: No module named 'classify'

### ISSUE THREAD

**Issue by mherschl** [abugoot-lab/pegRNA_rank#1]
I'm getting this error with line 137 of rank.py. After installing classify with `pip install classify`, I am getting another error: AttributeError: Can't get attribute 'twolayermlp'. Any idea how to fix this?

**Comment by idmjky** [comment]
Hi, 
Without knowing your current conda/python environment, I would suggest creating a new conda environment and then run the install command inside a clean anaconda environment to make sure the right version of the torch is installed for loading in the model (mlp.pt). You would not need to install classify separately using pip if you run the original install command.

**Comment by mherschl** [comment]
Thank you, here is what I tried:
```
conda create -n rank python=3.6
conda activate rank
conda install pytorch==1.5.1 torchvision==0.6.1 -c pytorch
pip install -r requirements.txt
python rank.py
```
This did not change when I did not specify the package versions (python=3.9.7 pytorch=1.7.1) or when I did not install pytorch before installing requirements.txt

**Comment by idmjky** [comment]
Hi, sorry for the late response. I just updated the depository with a new yml file. You can try creating the conda environment by directly cloning the paste.yml and see if you can run through the program.

**Comment by mherschl** [comment]
Thank you for uploading. I tried running in the environment created from the .yml file and got the same error:

```
conda create env -f paste.yml
conda activate ML
python rank.py
```

**Comment by idmjky** [comment]
Hi, 
I have added a file called classify.py that specify the structure of the torch model to avoid error message from torch loading itself. Please try re-cloning the path and try it out. Hope it works for you
